image: python:3.10

before_script:
  - python -V  # Print out python version for debugging
  - pip install pdm

stages:          # List of stages for jobs, and their order of execution
  - Build
  - Test

test:
  stage: Test
  script:
    - pip install tox flake8
    # stop the build if there are Python syntax errors or undefined names
    - pdm run flake8 ./src --count --select=E9,F63,F7,F82 --show-source --statistics
    # exit-zero treats all errors as warnings
    - pdm run flake8 ./src --count --exit-zero --max-complexity=20 --max-line-length=127 --statistics
    - pdm run tox
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:
  stage: Build
  script: 
    - pdm install
    - pdm build
  artifacts:
    paths:
      - dist/*.whl

