{
 "title": "Main NVCL Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Borehole Count and Kilometres Scanned for this FY",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT provider as 'Provider', sum(stat_val1) as 'Count', sum(stat_val2) as 'Kilometres' from stats\nwhere DATE(start_date) < DATE('now') and DATE(end_date) > DATE('now')\nand DATE(end_date) > DATE(start_date, '+11 months') -- remove quarterly data\nand stat_name = 'borehole_cnt_kms'\ngroup by provider\norder by provider\n--SELECT * from stats;\n",
     "rawQueryText": "SELECT provider as 'Provider', sum(stat_val1) as 'Count', sum(stat_val2) as 'Kilometres' from stats\nwhere DATE(start_date) < DATE('now') and DATE(end_date) > DATE('now')\nand DATE(end_date) > DATE(start_date, '+11 months') -- remove quarterly data\nand stat_name = 'borehole_cnt_kms'\ngroup by provider\norder by provider\n--SELECT * from stats;\n"
    }
   ]
  },
  {
   "title": "Provider borehole count bar graph",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "select distinct provider, count(distinct borehole_id) as \"borehole count\" from meas group by provider;",
     "rawQueryText": "select distinct provider, count(distinct borehole_id) as \"borehole count\" from meas group by provider;"
    }
   ]
  },
  {
   "title": "Borehole Count and Kilometres Scanned for this Quarter",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT provider as 'Provider', sum(stat_val1) as 'Count', sum(stat_val2) as 'Kilometres' from stats\nwhere DATE(start_date) < DATE('now') and DATE(end_date) > DATE('now')\nand DATE(end_date) < DATE(start_date, '+4 months') -- remove yearly data\nand stat_name = 'borehole_cnt_kms'\ngroup by provider\norder by provider\n--SELECT * from stats;\n",
     "rawQueryText": "SELECT provider as 'Provider', sum(stat_val1) as 'Count', sum(stat_val2) as 'Kilometres' from stats\nwhere DATE(start_date) < DATE('now') and DATE(end_date) > DATE('now')\nand DATE(end_date) < DATE(start_date, '+4 months') -- remove yearly data\nand stat_name = 'borehole_cnt_kms'\ngroup by provider\norder by provider\n--SELECT * from stats;\n"
    }
   ]
  },
  { "title": "Other NVCL Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 } }
 ]
}