apiVersion: batch/v1
kind: CronJob
metadata:
  name: run-db-update
spec:
  # Every Monday at 9am
  schedule: "0 9 * * 1"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: runner
            image: ubuntu:latest
            command: ["/bin/sh", "/scripts/script.sh", "{{ .Values.nfs.security.userId }}"]
            envFrom:
              - secretRef:
                  name: postgres-secret
            resources:
              requests:
                cpu: 6
                memory: 64Gi
              limits:
                cpu: 6
                memory: 64Gi
            volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: nvcl-fs
              mountPath: /nvcl-fs
            - name: nvcl-disk
              mountPath: /nvcl-disk
          volumes:
          - name: scripts
            configMap:
              name: my-script
              defaultMode: 0755
          - name: nvcl-fs
            nfs:
              server: {{ .Values.nfs.vols.nvclDb.server }}
              path: {{ .Values.nfs.vols.nvclDb.path }}
          - name: nvcl-disk
            persistentVolumeClaim:
              claimName: nvcl-pvc
          securityContext:
            runAsUser: 0
