apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nvcl-projects
type: Opaque
stringData:
  POSTGRES_DB: <db-name-here>
  POSTGRES_USER: <db-user-here>
  POSTGRES_PASSWORD: <db-password-here>
