apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nvcl-db
  name: nvcl-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
