#!/usr/bin/env python3

import csv
import logging
import os
import sys
import datetime
import pandas as pd
from urllib.parse import urlparse
from pathlib import PurePosixPath

# Import CSV fields from source
from tsg_harvest.harvest import HL_SCAN_DATE, TSG_PUBLISH_DATE, NVCL_ID

logger = logging.getLogger(__name__)

"""
This class reads Hylogger metadata from a CSV file
CSV file is generated by 'harvest.py' script in tsg_harvest directory
"""
class TSGMeta:
    def __init__(self, csv_filename: str, nvclstore: bool = False):
        """ Converts the CSV file into a dict, first column is NVCL id, second column date

            :param csv_filename: filename and path of CSV file
            :param nvclstore: CSV file is NVCL store format or NCI's NVCL TSG file collection
        """
        self.table = {}
        nvcl_ids = {}
        if os.path.exists(csv_filename):
            with open(csv_filename) as csvfile:
                if not nvclstore:
                    # From NVCL's TSG file store
                    tsg_reader = csv.DictReader(csvfile, delimiter='|')
                    scan_date_header = HL_SCAN_DATE
                    publish_date_header = TSG_PUBLISH_DATE
                    nvcl_id_header = NVCL_ID
                else:
                    # From NCI's NVCL TSG file collection
                    tsg_reader = csv.DictReader(csvfile)
                    # These are the equivalents of NVCL_ID, HL_SCAN_DATE and TSG_PUBLISH_DATE in NVCL store
                    scan_date_header = 'Source last Modified'
                    publish_date_header = 'FileModifiedDate'
                    nvcl_id_header = 'BoreholeURI'
                # Read CSV file
                for row in tsg_reader:
                    if nvcl_id_header == 'BoreholeURI':
                        # If it is a borehole URI, only use the last part of the path
                        nvcl_id = PurePosixPath(urlparse(row[nvcl_id_header]).path).name
                    else:
                        nvcl_id = row[nvcl_id_header]
                    scan_date = self.__str2date(row[scan_date_header], nvclstore)
                    publish_date = self.__str2date(row[publish_date_header], nvclstore)
                    # Is this NVCL id already in the dict?
                    if nvcl_id in nvcl_ids:
                        continue
                    nvcl_ids[nvcl_id] = True
                    # Assemble dict for pandas row  ( nvcl_id, scan date, publish date )
                    self.table.setdefault('nvcl_id', []).append(nvcl_id)
                    self.table.setdefault(HL_SCAN_DATE, []).append(scan_date)
                    self.table.setdefault(TSG_PUBLISH_DATE, []).append(publish_date)
        else:
            logger.error("Cannot find TSG metadata file: %s", csv_filename)
            sys.exit(1)

    def __str2date(self, date_str: str, nvclstore: bool) -> datetime.date:
        """ Converts date string to datetime.date object

        :param date_str: date string in '%Y-%m-%d %H:%M:%S' or 'DD/MM/YYYY'format
        :param nvclstore: use NVCL store date format or TSG date format
        :returns: datetime.date object
        """
        if nvclstore is True:
            try:
                return datetime.datetime.strptime(date_str, '%d/%m/%Y').date()
            except ValueError:
                return None
        try:
            return datetime.datetime.strptime(date_str, '%Y-%m-%d %H:%M:%S').date()
        except ValueError:
            return None

    def get_frame(self) -> pd.DataFrame:
        """ Returns a pandas DataFrame with nvcl_id, HL_SCAN_DATE and TSG_PUBLISH_DATE  columns
        """
        return pd.DataFrame(self.table)
