name: Run linter and tests
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v7
    - run: python -V
    - run: pip install --upgrade pip
    - run: pip install pdm
    - run: pdm install
    - run: pdm build
    - uses: actions/upload-artifact@v7
      if: success()
      with:
        name: "${{ github.job }}"
        path: dist/*.whl
  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd "pg_isready -U postgres -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/test_db
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v7
    - uses: actions/download-artifact@v8
    - run: apt install postgresql postgresql-contrib
    - run: python -V
    - run: pip install pdm
    - run: pip install tox flake8
    - run: pdm run flake8 ./src --count --select=E9,F63,F7,F82 --show-source --statistics
    - run: pdm run flake8 ./src --count --exit-zero --max-complexity=20 --max-line-length=127 --statistics
    - run: pdm run tox
    - name: Install rsync for test badge deploy action
      run: |
        apt-get update && apt-get install -y rsync
    - name: Deploy test badge to main branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: test/badge
          target-folder: test/badge
          branch: main
